In [24]:
import numpy as np

In [25]:
x = [1,2,3,4]
y = [4,5,6,7]
z = []

In [26]:
for i,j in zip(x,y):
    z.append(i+j)

In [27]:
print(z)

[5, 7, 9, 11]


In [28]:
np.add(x,y)

array([ 5,  7,  9, 11])

In [34]:
x1 = np.arange(2,10)

In [37]:
x2 = np.arange(12,20)

In [38]:
def multiofTwo(x,y):
    return x*y

In [30]:
newmf=np.frompyfunc(multiofTwo,2, 1)

In [31]:
print(newmf)

<ufunc 'multiofTwo (vectorized)'>


In [39]:
print(multiofTwo(x1,x2))

[ 24  39  56  75  96 119 144 171]


In [44]:
print(type(np.add))

<class 'numpy.ufunc'>


In [46]:
print(type(np.concatenate))

<class 'function'>


In [49]:
np.multiply(x1,x2)

array([ 24,  39,  56,  75,  96, 119, 144, 171])

In [50]:
np.divide(x1,x2)

array([0.16666667, 0.23076923, 0.28571429, 0.33333333, 0.375     ,
       0.41176471, 0.44444444, 0.47368421])

In [51]:
np.divmod(x1,x2)

(array([0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32))

In [52]:
np.remainder(x1,x2)

array([2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [53]:
np.power(x2,x1)

array([        144,        2197,       38416,      759375,    16777216,
         410338673, -1864941312,   565150579], dtype=int32)

In [54]:
np.subtract(x2,x1)

array([10, 10, 10, 10, 10, 10, 10, 10])