In [36]:
import numpy as np

In [37]:
arr1 = np.array([1,3,4])

In [38]:
arr2 = np.array([5,6,7])

In [39]:
nw_arr = np.stack((arr1,arr2),axis=1)

In [42]:
nw_arrh = np.hstack((arr1,arr2))

In [43]:
nw_arr1

array([1, 3, 4, 5, 6, 7])

In [44]:
nw_arrv = np.vstack((arr1,arr2))

In [45]:
nw_arrv

array([[1, 3, 4],
       [5, 6, 7]])

In [46]:
nw_arrd = np.dstack((arr1,arr2))

In [47]:
nw_arrd

array([[[1, 5],
        [3, 6],
        [4, 7]]])

In [30]:
arr1 = np.array([[0,12,14],[23,45,55]])

In [31]:
arr2 = np.array([[0,12,14],[23,45,55]])

In [32]:
new_arr= np.concatenate((arr1,arr2),axis = 1)

In [33]:
new_arr

array([[ 0, 12, 14,  0, 12, 14],
       [23, 45, 55, 23, 45, 55]])

In [48]:
arrlist = np.array([1,2,4,5,6,7,8,0,3])

In [52]:
np.array_split(arrlist, 4)

[array([1, 2, 4]), array([5, 6]), array([7, 8]), array([0, 3])]

In [56]:
np.array_split([[1,2],[3,4],[6,7]],3,axis=1)

[array([[1],
        [3],
        [6]]),
 array([[2],
        [4],
        [7]]),
 array([], shape=(3, 0), dtype=int32)]

In [57]:
np.where(arrlist == 0)

(array([7], dtype=int64),)

In [58]:
np.where(arrlist%2 ==0)

(array([1, 2, 4, 6, 7], dtype=int64),)

In [67]:
arrlist.sort()

In [68]:
arrlist

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
np.searchsorted(arrlist,11)

9

In [69]:
animal_name= np.array(['Zebra','Camel','Goat','Cow','Ambush','Modi'])

In [72]:
print(np.sort(animal_name))

['Ambush' 'Camel' 'Cow' 'Goat' 'Modi' 'Zebra']


In [73]:
marks_arr = np.array([24,46,89,26,55,77,0,100])

In [74]:
check_con = marks_arr>26

In [79]:
new_arry = marks_arr[check_con]

In [81]:
new_arry

array([ 46,  89,  55,  77, 100])

In [82]:
check_con


array([False,  True,  True, False,  True,  True, False,  True])